### ISSUE TITLE
Why this library is deprecated? What should I use instead of this library?

### ISSUE THREAD

**Issue by galcyurio** [anothem/android-range-seek-bar#106]
Description section show me following message.
````
[DEPRECATED] It provides a SeekBar similar to the default Android one, but with two thumb controls allowing a range to be selected, and some other extras as well.
````

Where is the new library which I use instead?
README.md doesn't show me what is replacement.

**Comment by anothem** [comment]
I marked it as deprecated because I don't have time to maintain it any more and it hasn't been receiving updates or bugfixes for a long time. That doesn't stop you from using it or any of the code, if it's good enough for what you need.
