### ISSUE TITLE
Setting maximum range  to time duration of video

### ISSUE THREAD

**Issue by bhuvneshvarma** [anothem/android-range-seek-bar#14]
Suppose i am playing a video and using this range seek bar for selecting time range of video.can i set the maximium range according to the time duration of video?Or the ranges will always be from 0-100.

**Comment by anothem** [comment]
Please look at the sample app before opening an issue, these questions should be answered by that code & XML. Yes, you can set the range values, either in XML or Java code.

**Comment by dbachelder** [comment]
I think he wants it formatted as time 0:00 - 2:34 or something
