### ISSUE TITLE
Gradle Version in AAR is out of date

### ISSUE THREAD

**Issue by GrouchyPanda** [anothem/android-range-seek-bar#17]
When trying to import the gradle version of the library into my current project, I was receiving an issue with the ic_launcher.png being duplicated within my project and the library. Upon looking into this, I found [this](http://stackoverflow.com/questions/29965398/gradle-finished-with-non-zero-exit-value-1-ic-launcher-png-error-duplicate-fi) which says that the problem arises because the version of the gradle plugin being used in the library is out of date with my current plugin version. In looking at the source, the library is currently using version 1.1.0 while the current release version is 1.2.3. If you could please update the build to correct this issue, that would help with further compatibility issues.

**Comment by anothem** [comment]
The bug causing this has also been fixed, but just haven't made a new release yet. It's coming soon, but in the meantime, you can either grab the latest in code or the SNAPSHOT build which has the fix. But will update the gradle version as well, thanks for that.

**Comment by anothem** [comment]
Gradle version updated on https://github.com/anothem/android-range-seek-bar/pull/21
Also on SNAPSHOT build now (use org.florescu.android.rangeseekbar:rangeseekbar-library:0.3.0-SNAPSHOT)
