### ISSUE TITLE
Anyway to remove the word min and max and change thumbs color?

### ISSUE THREAD

**Issue by donpironet** [anothem/android-range-seek-bar#22]
Is there any way to remove the words Min and Max before and after the bar? 
Edit: I don't find any method to change the thumbs colors from blue to something else?

Thanks in advantage.

**Comment by sewar** [comment]
Yes, you can set that in XML only:
```
rsb:showLabels="false"
```

**Comment by donpironet** [comment]
The rsb showLabels doesn't work i'm having it like this:

  <org.florescu.android.rangeseekbar.RangeSeekBar
            android:id="@+id/rangeBar"
            android:layout_centerVertical="true"
            android:layout_width="220dp"
            android:layout_height="200dp"
            rsb:showLabels="false"/>

**Comment by sewar** [comment]
Try this, and make sure you use latest version from gradle:
```
<com.yahoo.mobile.client.android.util.rangeseekbar.RangeSeekBar
	xmlns:rsb="http://schemas.android.com/apk/res-auto"
	android:id="@+id/rangeBar"
	android:layout_centerVertical="true"
	android:layout_width="220dp"
	android:layout_height="200dp"
	rsb:showLabels="false"/>
```

**Comment by donpironet** [comment]
i'm using gradle 1.3.0. I removed the app rebuild and still the same problem. But my rangeseekbar is this one:

<org.florescu.android.rangeseekbar.RangeSeekBar

**Comment by sewar** [comment]
Yes that's the new package name, I'm using the old version and it works fine for me. Is your project on Github?

**Comment by donpironet** [comment]
No it's not on github. It's a private project. But I copied your code with the new package like I showed you and it doens't work.

**Comment by sewar** [comment]
I updated my project to use `org.florescu.android.rangeseekbar:rangeseekbar-library:0.2.0` and it works fine.

**Comment by anothem** [comment]
@donpironet, do you still have this problem? Could you also share your build.gradle file?

**Comment by donpironet** [comment]
Sorry for the late response. I did had the same problem but I just dropped the idea to do it with a rangebar because the project had a quick release.

**Comment by anothem** [comment]
No worries and sorry to hear that. If there is any way we can repro the problem, I'll dig more into it, so let me know if there's anything else you can share. Otherwise I'll have to close this issue for now.
