### ISSUE TITLE
How to remove the progress?

### ISSUE THREAD

**Issue by praveenbroski** [anothem/android-range-seek-bar#27]
Please help me with removing the progress shown above the seekbar. I have separate TextView's to perform this task.
![device-2015-09-17-172747](https://cloud.githubusercontent.com/assets/14329980/9932459/ac0e44d8-5d61-11e5-8381-4a9260845d96.png)
My need was shown in the above figure rounded. Please tell a way to remove it.
Thanks.

**Comment by anothem** [comment]
You can disable them from either XML or Java. Check out the demo app. 
https://github.com/anothem/android-range-seek-bar/blob/master/rangeseekbar-sample/src/main/res/layout/main.xml#L125

**Comment by praveenbroski** [comment]
Worked. Thanks.
