### ISSUE TITLE
Anyway to freeze min thumb?

### ISSUE THREAD

**Issue by Reegan01** [anothem/android-range-seek-bar#28]
In my project I used your Library. I want to freeze the thumb certain value. can I able to do this?

This is wonderful library and thanks to you ..

**Comment by anothem** [comment]
Sorry, I'm not sure I understand what you need. What exactly do you mean by freeze? Do you want it to not move at all or just not move beyond a certain value?

**Comment by Reegan01** [comment]
If I have max and min value in the database. I want to get the min and max value and set the seek bar. If min and max value is fixed. user can't move the thumb. Thank you for your Response ..God Bless

**Comment by anothem** [comment]
So in that case are you using the bar just to show some values, but the user cannot take any action?

**Comment by Reegan01** [comment]
Yes bro ..

**Comment by anothem** [comment]
No, I'm afraid that's not a supported feature and probably not on the roadmap anytime soon. It's a very specific use-case, so I think best handled on case by case basis rather than as a library feature. Sorry :(
