### ISSUE TITLE
Not showing values a default values.

### ISSUE THREAD

**Issue by MaxiSch** [anothem/android-range-seek-bar#29]
Hello, I need to see the values at default positions. This attr seems to be what I am needing, but I can't compile. I get: Error:(212) No resource identifier found for attribute 'activateOnDefaultValues' in package. Could you check please? Thanks for your help!

        <attr name="activateOnDefaultValues" format="boolean"/>

**Comment by anothem** [comment]
Hi @MaxiSch, how are you using the app? Source or as a gradle lib? 
I've only updated the SNAPSHOT build this morning, so that's the only one that has this change at the moment.

**Comment by MaxiSch** [comment]
Hi @anothem is your SNAPSHOT this one?
'org.florescu.android.rangeseekbar:rangeseekbar-library:0.3.0-SNAPSHOT'? Because I still can't see the changes.

I'm not sure what you mean with your question. I only added your api to the dependencies.

Thanks!

**Comment by anothem** [comment]
Yup, that's what I wanted to check. Not sure what's wrong, I just tested it with the snapshot build and it's fine for me. Maybe share your xml file?

**Comment by MaxiSch** [comment]
Sure, this is the actual XML:
<org.florescu.android.rangeseekbar.RangeSeekBar
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        rsb:textAboveThumbsColor="#000000"
                        rsb:defaultColor="#000000"
                        rsb:alwaysActive="true"
                        rsb:showLabels="false"
                        android:layout_weight="5"
                        android:id="@+id/rangeAge"
                        />

And this is what I want:

<org.florescu.android.rangeseekbar.RangeSeekBar
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        rsb:textAboveThumbsColor="#000000"
                        rsb:defaultColor="#000000"
                        rsb:alwaysActive="true"
                        rsb:showLabels="false"
                        rsb:ActivateOnDefaultValues="true"
                        android:layout_weight="5"
                        android:id="@+id/rangeAge"
                        />

rsb:ActivateOnDefaultValues="true" is giving this problem:
Error:(212) No resource identifier found for attribute 'ActivateOnDefaultValues' in package 'com.example.tp.huellitas'

**Comment by anothem** [comment]
Attributes are case sensitive, try lowercase a. 
rsb:activateOnDefaultValues

**Comment by MaxiSch** [comment]
Thanks man! I swear a tried that, but it failed. I think it must be because I was on the released version.
Now in lower case, it works in SNAPSHOT. 

Thanks for your time!

**Comment by anothem** [comment]
No worries, glad it works :)
