### ISSUE TITLE
I want to add Euro text above range seek bar text when user change value.

### ISSUE THREAD

**Issue by bhaveshkaila** [anothem/android-range-seek-bar#41]
![Uploading Capture.PNG…]()
Hi anothem,

I want to add euro sign with changed values when user change values of range seek bar i have attached image also can you please help me how can I achieve this using range seek bar.

**Comment by bhaveshkaila** [comment]
I have resolve this by changes in library.

Rhanks

**Comment by SteveKamau72** [comment]
What were your changes? Please share
