### ISSUE TITLE
cannot resolve symbol "RangeSeekBar"

### ISSUE THREAD

**Issue by MoshDev** [anothem/android-range-seek-bar#42]
after the last update, the RangeSeekBar class doesn't exists anymore!!

**Comment by anothem** [comment]
Can you show how you're importing (e.g. gradle file) and how you're using it in code/XML?

**Comment by MoshDev** [comment]
it was working fine yesterday, until today i refreshed dependencies, nothing unusual, the used version was imported 1 month ago, and now it won't resolve for 0.3.0

<org.florescu.android.rangeseekbar.RangeSeekBar
      android:layout_width="match_parent"
      android:id="@+id/rangeSeekBar"
      app:showLabels="false"
      app:valuesAboveThumbs="false"
      android:layout_height="wrap_content"
      app:absoluteMinValue="0"
      app:absoluteMaxValue="100"
      />

**Comment by MoshDev** [comment]
seems there is something wrong with gradle, or building-tools, i want to make sure its not from your side, I apologize for any trouble

**Comment by anothem** [comment]
No trouble, let me know if I can help.
