### ISSUE TITLE
Snapshot version not working

### ISSUE THREAD

**Issue by chintansoni202** [anothem/android-range-seek-bar#62]
While using the snapshot version, gradle build fails:

dependencies {
        compile 'org.florescu.android.rangeseekbar:rangeseekbar-library:0.4.0-SNAPSHOT'
}

It says: 

Error:(51, 13) Failed to resolve: org.florescu.android.rangeseekbar:rangeseekbar-library:0.4.0-SNAPSHOT
<a href="openFile:/home/ln-202/Chintan/GitLab Projects/IdolBee/source/SHVDIA_IDOLBEE/IdolBee/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

Please update the doc if already fixed..

**Comment by anothem** [comment]
Sample builds on CI so it should be fine: https://travis-ci.org/anothem/android-range-seek-bar/builds/113207989

Have you added the snapshots repository? 
https://github.com/anothem/android-range-seek-bar/blob/master/rangeseekbar-sample/build.gradle#L3-L5
