### ISSUE TITLE
Snapshot not available

### ISSUE THREAD

**Issue by gradha** [anothem/android-range-seek-bar#72]
Using:
```
    compile 'org.florescu.android.rangeseekbar:rangeseekbar-library:0.4.0-SNAPSHOT'
```
shows the error:
```
14:37:25 Gradle sync failed: Could not find org.florescu.android.rangeseekbar:rangeseekbar-library:0.4.0-SNAPSHOT.
```

**Comment by anothem** [comment]
Are you including the snapshot repository? 
https://github.com/anothem/android-range-seek-bar/blob/master/rangeseekbar-sample/build.gradle#L3-L5

**Comment by gradha** [comment]
Wasn't aware of that, it works after adding it.
