### ISSUE TITLE
Ability to set initial value or default value.

### ISSUE THREAD

**Issue by uDevel** [anothem/android-range-seek-bar#75]
Maybe someone can help me here.  Is there a way to set initial value or default value?
Currently, it's min and max.
For single value, it's always max.

**Comment by anothem** [comment]
You can do it in code. Example:
https://github.com/anothem/android-range-seek-bar/blob/master/rangeseekbar-sample/src/main/java/org/florescu/android/rangeseekbar/sample/DemoActivity.java#L40-L41

**Comment by christhornham** [comment]
You can use setSelectedMinValue() and setSelectedMaxValue() when you have two thumbs.  If I set `singleThumb="true"`, how can I set the selected value of the single thumb?

Thanks!
