### ISSUE TITLE
How can use OnRangeSeekBarChangeListener. Does not work in Android Stidio...

### ISSUE THREAD

**Issue by Lopner** [anothem/android-range-seek-bar#89]
Hi. 
I try to use OnRangeSeekBarChangeListener. I take your project, import in Android Studio on my PC, and in **rangeseekbar-sample/../DemoActivity.java** have add this:

`RangeSeekBar<Integer> rangeSeekBar= new RangeSeekBar<Integer>(this);
seekBar.setRangeValues(0, 100);

rangeSeekBar.setOnRangeSeekBarChangeListener(new RangeSeekBar.OnRangeSeekBarChangeListener<Integer>() {
    @Override
public void onRangeSeekBarValuesChanged(RangeSeekBar<?> bar, Integer minValue, Integer maxValue) {

    }
});`

Android Studio emphasize "RangeSeekBar.OnRangeSeekBarChangeListener" whit message:
"Class 'Anonymous class derived from OnRangeSeekBarChangeListener' must either be declared or implement abstract method 'onRangeSeekBarValuesChanged(RangeSeek...' "

I don't understand what I should to do, to make it run.. Please help with this problem.

**Comment by anothem** [comment]
Without the error I can't tell exactly what the problem is. But that signature doesn't look right, it should be:
`public void onRangeSeekBarValuesChanged(RangeSeekBar<Integer> bar, Integer minValue, Integer maxValue) {`

**Comment by Lopner** [comment]
Thanks, now everything works!
