### ISSUE TITLE
How can draw Min and Max value when rangeseekbar changed to Min and Max?

### ISSUE THREAD

**Issue by Lopner** [anothem/android-range-seek-bar#93]
Hi!) 
If i change rangeeseekbar to Min and Max values, the lables above a touch circles be disappear. What can make to paint in this case lables with values?

**Comment by anothem** [comment]
There is a property, `alwaysActive`. Set that to `true` in the XML and it won't disable on default anymore.

**Comment by deepak786** [comment]
`alwaysActive` is not working for me. But `activateOnDefaultValues` works. I'm using 'compile 'org.florescu.android.rangeseekbar:rangeseekbar-library:0.3.0'
