### ISSUE TITLE
RangeSeekBar and SharedPreferences issues and temporal solutions

### ISSUE THREAD

**Issue by iaraya26** [anothem/android-range-seek-bar#95]
I have the following XLM piece of code to instantiate the rangeSeekBar:

```
<com.crystal.crystalrangeseekbar.widgets.CrystalRangeSeekbar
            android:id="@+id/rangeSeekbar1"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:corner_radius="10"
            app:min_value="0"
            app:max_value="88"
            app:gap="24"
            app:bar_color="#8990C4"
            app:bar_highlight_color="#2434AD"
            app:left_thumb_color="#1A246D"
            app:right_thumb_color="#1A246D"
            app:left_thumb_color_pressed="#030B47"
            app:right_thumb_color_pressed="#030B47"
            app:data_type="_integer"/>
```

To save preferences, use this in your onPause method:

// SAVE PREFERENCES
```
CrystalRangeSeekbar rangeSeekbar = (CrystalRangeSeekbar) findViewById(R.id.rangeSeekbar1);
SharedPreferences settings = getSharedPreferences(PREFS, 0);
SharedPreferences.Editor editor = settings.edit();

editor.putInt("minVal", rangeSeekbar.getSelectedMinValue().intValue());
editor.putInt("maxVal", rangeSeekbar.getSelectedMaxValue().intValue());

editor.apply();

```

To restore preferences, use this in your onCreate method:

//RESTORE PREFERENCES

```
SharedPreferences settings = getSharedPreferences(PREFS, 0);
final CrystalRangeSeekbar rangeSeekbar = (CrystalRangeSeekbar) findViewById(R.id.rangeSeekbar1);

rangeSeekbar.setGap(24).setMinStartValue(settings.getInt("minVal",0)).setMaxStartValue(settings.getInt("maxVal",87)).apply(); 

```
Don't forget to declare this at the beginning of your class:

`public static final String PREFS= "MyPREFS"; `

SO, THESE ARE THE ISSUES:

1) It's important to restore every rangeSeekBar setting using a single line like I showed before. I tried restoring the gap, minStartValue and maxStartValue independently and it was a complete mess, it just doesn't work. 

2) If you don't use the setter to redefine the gap number, you won't be able to save your data correctly, even if you wrote the XML definition before, and the rangeSeekBar thumbs will be unpredictable.

NOTE:
a) setGap(yourgap) - it has to coincide with your XML definition. 
b) settings.getInt("minVal",yourminimumvalue)
c) settings.getInt("maxVal",yourmaximumvalue)

**Comment by anothem** [comment]
I believe you're using a different seekbar. It seems like you're referring to : https://github.com/syedowaisali/crystal-range-seekbar
